// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rip_fileitf/rip_fileitf.proto

package rip_fileitf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileReqItf_OpenFile_Prm struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_OpenFile_Prm) Reset()         { *m = FileReqItf_OpenFile_Prm{} }
func (m *FileReqItf_OpenFile_Prm) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_OpenFile_Prm) ProtoMessage()    {}
func (*FileReqItf_OpenFile_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{0}
}

func (m *FileReqItf_OpenFile_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_OpenFile_Prm.Unmarshal(m, b)
}
func (m *FileReqItf_OpenFile_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_OpenFile_Prm.Marshal(b, m, deterministic)
}
func (m *FileReqItf_OpenFile_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_OpenFile_Prm.Merge(m, src)
}
func (m *FileReqItf_OpenFile_Prm) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_OpenFile_Prm.Size(m)
}
func (m *FileReqItf_OpenFile_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_OpenFile_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_OpenFile_Prm proto.InternalMessageInfo

func (m *FileReqItf_OpenFile_Prm) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type FileReqItf_OpenFile_Ret struct {
	FileCode             int64    `protobuf:"varint,1,opt,name=fileCode,proto3" json:"fileCode,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_OpenFile_Ret) Reset()         { *m = FileReqItf_OpenFile_Ret{} }
func (m *FileReqItf_OpenFile_Ret) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_OpenFile_Ret) ProtoMessage()    {}
func (*FileReqItf_OpenFile_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{1}
}

func (m *FileReqItf_OpenFile_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_OpenFile_Ret.Unmarshal(m, b)
}
func (m *FileReqItf_OpenFile_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_OpenFile_Ret.Marshal(b, m, deterministic)
}
func (m *FileReqItf_OpenFile_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_OpenFile_Ret.Merge(m, src)
}
func (m *FileReqItf_OpenFile_Ret) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_OpenFile_Ret.Size(m)
}
func (m *FileReqItf_OpenFile_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_OpenFile_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_OpenFile_Ret proto.InternalMessageInfo

func (m *FileReqItf_OpenFile_Ret) GetFileCode() int64 {
	if m != nil {
		return m.FileCode
	}
	return 0
}

func (m *FileReqItf_OpenFile_Ret) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type FileReqItf_Read_Prm struct {
	FileCode             int64    `protobuf:"varint,1,opt,name=fileCode,proto3" json:"fileCode,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_Read_Prm) Reset()         { *m = FileReqItf_Read_Prm{} }
func (m *FileReqItf_Read_Prm) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_Read_Prm) ProtoMessage()    {}
func (*FileReqItf_Read_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{2}
}

func (m *FileReqItf_Read_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_Read_Prm.Unmarshal(m, b)
}
func (m *FileReqItf_Read_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_Read_Prm.Marshal(b, m, deterministic)
}
func (m *FileReqItf_Read_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_Read_Prm.Merge(m, src)
}
func (m *FileReqItf_Read_Prm) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_Read_Prm.Size(m)
}
func (m *FileReqItf_Read_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_Read_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_Read_Prm proto.InternalMessageInfo

func (m *FileReqItf_Read_Prm) GetFileCode() int64 {
	if m != nil {
		return m.FileCode
	}
	return 0
}

func (m *FileReqItf_Read_Prm) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *FileReqItf_Read_Prm) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileReqItf_Read_Ret struct {
	AccessCode           int32    `protobuf:"varint,1,opt,name=accessCode,proto3" json:"accessCode,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_Read_Ret) Reset()         { *m = FileReqItf_Read_Ret{} }
func (m *FileReqItf_Read_Ret) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_Read_Ret) ProtoMessage()    {}
func (*FileReqItf_Read_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{3}
}

func (m *FileReqItf_Read_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_Read_Ret.Unmarshal(m, b)
}
func (m *FileReqItf_Read_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_Read_Ret.Marshal(b, m, deterministic)
}
func (m *FileReqItf_Read_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_Read_Ret.Merge(m, src)
}
func (m *FileReqItf_Read_Ret) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_Read_Ret.Size(m)
}
func (m *FileReqItf_Read_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_Read_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_Read_Ret proto.InternalMessageInfo

func (m *FileReqItf_Read_Ret) GetAccessCode() int32 {
	if m != nil {
		return m.AccessCode
	}
	return 0
}

func (m *FileReqItf_Read_Ret) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type FileReqItf_Write_Prm struct {
	FileCode             int64    `protobuf:"varint,1,opt,name=fileCode,proto3" json:"fileCode,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_Write_Prm) Reset()         { *m = FileReqItf_Write_Prm{} }
func (m *FileReqItf_Write_Prm) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_Write_Prm) ProtoMessage()    {}
func (*FileReqItf_Write_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{4}
}

func (m *FileReqItf_Write_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_Write_Prm.Unmarshal(m, b)
}
func (m *FileReqItf_Write_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_Write_Prm.Marshal(b, m, deterministic)
}
func (m *FileReqItf_Write_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_Write_Prm.Merge(m, src)
}
func (m *FileReqItf_Write_Prm) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_Write_Prm.Size(m)
}
func (m *FileReqItf_Write_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_Write_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_Write_Prm proto.InternalMessageInfo

func (m *FileReqItf_Write_Prm) GetFileCode() int64 {
	if m != nil {
		return m.FileCode
	}
	return 0
}

func (m *FileReqItf_Write_Prm) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *FileReqItf_Write_Prm) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileReqItf_Write_Ret struct {
	AccessCode           int32    `protobuf:"varint,1,opt,name=accessCode,proto3" json:"accessCode,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_Write_Ret) Reset()         { *m = FileReqItf_Write_Ret{} }
func (m *FileReqItf_Write_Ret) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_Write_Ret) ProtoMessage()    {}
func (*FileReqItf_Write_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{5}
}

func (m *FileReqItf_Write_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_Write_Ret.Unmarshal(m, b)
}
func (m *FileReqItf_Write_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_Write_Ret.Marshal(b, m, deterministic)
}
func (m *FileReqItf_Write_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_Write_Ret.Merge(m, src)
}
func (m *FileReqItf_Write_Ret) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_Write_Ret.Size(m)
}
func (m *FileReqItf_Write_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_Write_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_Write_Ret proto.InternalMessageInfo

func (m *FileReqItf_Write_Ret) GetAccessCode() int32 {
	if m != nil {
		return m.AccessCode
	}
	return 0
}

func (m *FileReqItf_Write_Ret) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type FileReqItf_MakeSureAccessCode_Prm struct {
	AccessCode           int32    `protobuf:"varint,1,opt,name=accessCode,proto3" json:"accessCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_MakeSureAccessCode_Prm) Reset()         { *m = FileReqItf_MakeSureAccessCode_Prm{} }
func (m *FileReqItf_MakeSureAccessCode_Prm) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_MakeSureAccessCode_Prm) ProtoMessage()    {}
func (*FileReqItf_MakeSureAccessCode_Prm) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{6}
}

func (m *FileReqItf_MakeSureAccessCode_Prm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_MakeSureAccessCode_Prm.Unmarshal(m, b)
}
func (m *FileReqItf_MakeSureAccessCode_Prm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_MakeSureAccessCode_Prm.Marshal(b, m, deterministic)
}
func (m *FileReqItf_MakeSureAccessCode_Prm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_MakeSureAccessCode_Prm.Merge(m, src)
}
func (m *FileReqItf_MakeSureAccessCode_Prm) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_MakeSureAccessCode_Prm.Size(m)
}
func (m *FileReqItf_MakeSureAccessCode_Prm) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_MakeSureAccessCode_Prm.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_MakeSureAccessCode_Prm proto.InternalMessageInfo

func (m *FileReqItf_MakeSureAccessCode_Prm) GetAccessCode() int32 {
	if m != nil {
		return m.AccessCode
	}
	return 0
}

type FileReqItf_MakeSureAccessCode_Ret struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReqItf_MakeSureAccessCode_Ret) Reset()         { *m = FileReqItf_MakeSureAccessCode_Ret{} }
func (m *FileReqItf_MakeSureAccessCode_Ret) String() string { return proto.CompactTextString(m) }
func (*FileReqItf_MakeSureAccessCode_Ret) ProtoMessage()    {}
func (*FileReqItf_MakeSureAccessCode_Ret) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8c7d1523b35364e, []int{7}
}

func (m *FileReqItf_MakeSureAccessCode_Ret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReqItf_MakeSureAccessCode_Ret.Unmarshal(m, b)
}
func (m *FileReqItf_MakeSureAccessCode_Ret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReqItf_MakeSureAccessCode_Ret.Marshal(b, m, deterministic)
}
func (m *FileReqItf_MakeSureAccessCode_Ret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReqItf_MakeSureAccessCode_Ret.Merge(m, src)
}
func (m *FileReqItf_MakeSureAccessCode_Ret) XXX_Size() int {
	return xxx_messageInfo_FileReqItf_MakeSureAccessCode_Ret.Size(m)
}
func (m *FileReqItf_MakeSureAccessCode_Ret) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReqItf_MakeSureAccessCode_Ret.DiscardUnknown(m)
}

var xxx_messageInfo_FileReqItf_MakeSureAccessCode_Ret proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FileReqItf_OpenFile_Prm)(nil), "rip_fileitf.FileReqItf_OpenFile_Prm")
	proto.RegisterType((*FileReqItf_OpenFile_Ret)(nil), "rip_fileitf.FileReqItf_OpenFile_Ret")
	proto.RegisterType((*FileReqItf_Read_Prm)(nil), "rip_fileitf.FileReqItf_Read_Prm")
	proto.RegisterType((*FileReqItf_Read_Ret)(nil), "rip_fileitf.FileReqItf_Read_Ret")
	proto.RegisterType((*FileReqItf_Write_Prm)(nil), "rip_fileitf.FileReqItf_Write_Prm")
	proto.RegisterType((*FileReqItf_Write_Ret)(nil), "rip_fileitf.FileReqItf_Write_Ret")
	proto.RegisterType((*FileReqItf_MakeSureAccessCode_Prm)(nil), "rip_fileitf.FileReqItf_MakeSureAccessCode_Prm")
	proto.RegisterType((*FileReqItf_MakeSureAccessCode_Ret)(nil), "rip_fileitf.FileReqItf_MakeSureAccessCode_Ret")
}

func init() {
	proto.RegisterFile("rip_fileitf/rip_fileitf.proto", fileDescriptor_d8c7d1523b35364e)
}

var fileDescriptor_d8c7d1523b35364e = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x3d, 0x4b, 0x03, 0x41,
	0x10, 0x86, 0x49, 0xce, 0xf8, 0x31, 0x22, 0xc8, 0x1a, 0xf0, 0x10, 0x14, 0x5d, 0x1b, 0x1b, 0xb5,
	0xf0, 0x17, 0x98, 0x80, 0xd1, 0x42, 0x94, 0xb1, 0xb0, 0x50, 0x38, 0x36, 0xc9, 0x1c, 0x2e, 0x46,
	0x6f, 0x9d, 0x1b, 0x1b, 0x7f, 0xbd, 0xec, 0x28, 0xc7, 0x82, 0x87, 0x07, 0x62, 0xf7, 0xce, 0xcb,
	0xce, 0xb3, 0x4f, 0x31, 0xb0, 0xcb, 0x3e, 0x14, 0xa5, 0x5f, 0x90, 0x97, 0xf2, 0x34, 0xc9, 0x27,
	0x81, 0x2b, 0xa9, 0xcc, 0x7a, 0x52, 0xd9, 0x63, 0xd8, 0xbe, 0xf0, 0x0b, 0x42, 0x7a, 0xbb, 0x92,
	0xb2, 0xb8, 0x09, 0xf4, 0x1a, 0xc7, 0xe2, 0x96, 0x5f, 0x8c, 0x81, 0xa5, 0xe0, 0xe4, 0x29, 0xef,
	0xed, 0xf7, 0x8e, 0xd6, 0x50, 0xb3, 0x9d, 0xb4, 0x3f, 0x47, 0x12, 0xb3, 0x03, 0xab, 0x11, 0x3a,
	0xae, 0xe6, 0xa4, 0x2b, 0x19, 0x36, 0xb3, 0xd9, 0x84, 0x8c, 0x98, 0xf3, 0xbe, 0x92, 0x62, 0xb4,
	0x0f, 0xb0, 0x95, 0x80, 0x90, 0xdc, 0x5c, 0xff, 0xfc, 0x0d, 0x32, 0x84, 0x41, 0x2d, 0x8e, 0x45,
	0x31, 0x19, 0x7e, 0x0d, 0xd1, 0xb2, 0xf6, 0x1f, 0x94, 0x67, 0x5a, 0x6a, 0xb6, 0x93, 0x9f, 0xf0,
	0x68, 0xb8, 0x07, 0xe0, 0x66, 0x33, 0xaa, 0xeb, 0x06, 0x3f, 0xc0, 0xa4, 0x69, 0xb1, 0x7c, 0x84,
	0x61, 0x02, 0xba, 0x67, 0x2f, 0xf4, 0x8f, 0x9a, 0x97, 0x2d, 0xf4, 0xbf, 0x79, 0x8e, 0xe1, 0x20,
	0x21, 0x5d, 0xbb, 0x67, 0xba, 0x7b, 0x67, 0x3a, 0x6f, 0x56, 0x54, 0xba, 0x03, 0x6b, 0x0f, 0xbb,
	0x20, 0x48, 0x32, 0xda, 0x80, 0x7e, 0x98, 0x8e, 0x56, 0xbe, 0xcf, 0x67, 0xba, 0xac, 0x27, 0x75,
	0xf6, 0x19, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xe8, 0x82, 0x20, 0x73, 0x02, 0x00, 0x00,
}
